---
# Including the always.yml playbook and applying the 'always' tag ensures that
# this role's tasks are executed regardless of the tags used by other playbooks

- name: Include tasks
  import_tasks: always.yml
  tags:
    - always
